title: Unideb.PlayGND
author: Brainstorming Lab Team
description: >-
  This site offers tutorials, open source projects, and various other
  tech-related content, from the Brainstorming Lab Team.

url: https://peterheim.github.io
baseurl: /demo-site/

theme: minima

collections:
  pages:
    output: true
    order: []
